import StatusBadge from '../../components/ui/StatusBadge.jsx'
import ProgressBar from '../../components/ui/ProgressBar.jsx'
import styles from './learningReviewSurface.module.css'

function Feedback({ feedback, onNext }) {
  const score = Number(feedback?.score)
  const label = feedback?.correct ? 'Remembered' : feedback?.almost || feedback?.nearCorrect || (Number.isFinite(score) && score > 0) ? 'Almost' : 'Revisit'
  return <section className="review-session-card" aria-live="polite"><div className="review-feedback-status"><StatusBadge status={label === 'Remembered' ? 'success' : label === 'Almost' ? 'progress' : 'warning'}>{label}</StatusBadge></div><p className="review-feedback-copy">{feedback?.explanation || 'No explanation provided.'}</p><div className="review-session-actions"><button className="ui-button ui-button-primary" type="button" onClick={onNext}>Next</button></div></section>
}

function Summary({ model, actions }) {
  const result = model.result || {}
  const items = result.perItemResults || []
  const correct = items.reduce((sum, item) => sum + (item.correctCount || 0), 0)
  const total = items.reduce((sum, item) => sum + (item.totalCount || 0), 0)
  return <section className="review-session-card review-session-summary" aria-labelledby="review-complete-title"><p className="ui-text-muted">Practice complete</p><h2 id="review-complete-title">{result.passed ? 'Ready to continue' : 'Revisit when ready'}</h2><div className="review-summary-score"><strong>{result.overallScore ?? 0}%</strong><span>{correct} remembered · {Math.max(0, total - correct)} to revisit</span></div>{result.accelerated && <StatusBadge status="progress">Next review spaced further</StatusBadge>}{result.regressed && <StatusBadge status="warning">More practice scheduled</StatusBadge>}{items.length > 0 && <section className="review-summary-items" aria-labelledby="review-by-chapter-title"><h3 id="review-by-chapter-title">By Chapter</h3>{items.map((item, index) => <div key={`${item.lessonTitle || item.chapterTitle || index}`}><span>{item.chapterTitle || item.moduleTitle || item.lessonTitle || 'Chapter review'}</span><StatusBadge status={item.score >= 80 ? 'success' : 'warning'}>{item.score}%</StatusBadge></div>)}</section>}<button className="ui-button ui-button-primary" type="button" onClick={actions.returnToTrail}>Continue Trail</button></section>
}

export default function ReviewSessionSurface({ model, className, variant }) {
  const { actions = {}, busy = {} } = model
  const current = model.currentQuestion
  if (model.phase === 'expired') return <main className={[styles.root, className].filter(Boolean).join(' ')} data-theme-view="ReviewSessionView" data-view-model="connected" data-pack-style={variant}><section className="review-session-card review-expired" aria-labelledby="missing-review-title"><h1 id="missing-review-title">Review session unavailable</h1><p>{model.error?.message || 'This review session is no longer available.'}</p><button type="button" className="ui-button ui-button-secondary" onClick={actions.returnToQueue}>Return to Review Queue</button></section></main>
  if (model.phase === 'complete') return <main className={[styles.root, className].filter(Boolean).join(' ')} data-theme-view="ReviewSessionView" data-view-model="connected" data-pack-style={variant}><Summary model={model} actions={actions} /></main>
  const isAnswering = model.phase === 'answers'
  return <main className={[styles.root, className].filter(Boolean).join(' ')} data-theme-view="ReviewSessionView" data-view-model="connected" data-pack-style={variant}>
    <header className="review-session-heading"><p className="ui-text-muted">Retrieval practice</p><h1>{current?.lessonTitle || 'Review session'}</h1><p>Question {isAnswering ? model.currentIndex + 1 : model.feedbackIndex + 1} of {model.totalQuestions}</p></header>
    <section className="review-session-progress" aria-label="Review progress"><ProgressBar value={isAnswering ? model.currentIndex + 1 : model.feedbackIndex + 1} max={model.totalQuestions} label="Review question progress" />{model.remainingCount > 0 && <p>{model.remainingCount} more retrieval item{model.remainingCount !== 1 ? 's' : ''} queued for later</p>}</section>
    {model.error && <div className="ui-alert ui-alert-danger" role="alert">{model.error.message}</div>}
    {model.phase === 'answer-review' && <section className="review-session-card" aria-labelledby="review-answer-list-title"><p className="ui-text-muted">Before feedback</p><h2 id="review-answer-list-title">Review your answers</h2><p className="ui-text-secondary">Your responses stay private until you submit the complete set.</p><ol className="review-answer-list">{model.questions.map((question, index) => <li key={question.id}><div><span>Question {index + 1}</span><h3>{question.text}</h3><p>{model.answers[question.id]}</p></div><button className="ui-button ui-button-secondary" type="button" onClick={() => actions.editAnswer(index)}>Edit answer</button></li>)}</ol><div className="review-session-actions"><button className="ui-button ui-button-secondary" type="button" onClick={actions.backToAnswers}>Back to questions</button><button className="ui-button ui-button-primary" type="button" onClick={actions.submit} disabled={busy.submitting}>{busy.submitting ? 'Submitting…' : 'Submit all answers'}</button></div></section>}
    {model.phase === 'feedback' && <Feedback feedback={model.currentFeedback} onNext={actions.nextFeedback} />}
    {isAnswering && current && <section className="review-session-card" aria-labelledby="review-question-title"><div className="review-question-meta"><span>Question {model.currentIndex + 1} of {model.totalQuestions}</span><StatusBadge status="neutral">{current.topicTitle || 'Review'}</StatusBadge></div><h2 id="review-question-title">{current.text}</h2><label htmlFor="review-answer" className="ui-field-label">Your answer</label><textarea id="review-answer" value={model.answers[current.id] || ''} onChange={(event) => actions.answer(current.id, event.target.value)} placeholder="Type your answer..." rows={4} className="ui-field w-full resize-y" disabled={busy.submitting} /><div className="review-session-actions">{model.currentIndex > 0 ? <button className="ui-button ui-button-secondary" type="button" onClick={actions.previousQuestion}>Previous</button> : <span />}{model.currentIndex < model.totalQuestions - 1 ? <button className="ui-button ui-button-primary" type="button" onClick={actions.nextQuestion} disabled={busy.submitting || !model.answers[current.id]?.trim()}>Next question</button> : <button className="ui-button ui-button-primary" type="button" onClick={actions.reviewAnswers} disabled={busy.submitting || !model.answers[current.id]?.trim()}>Review answers</button>}</div></section>}
  </main>
}
