export default {
  id: 'mission-workshop',
  name: 'Mission Workshop',
  mode: 'dark',
  tagline: 'A focused command center for deliberate practice.',
  previewAsset: '/themes/mission-workshop.webp',
  tokens: {
    canvas: '#151C20', panel: '#202A30', elevated: '#29363D', inset: '#101619', border: '#71878A', borderStrong: '#9CB1B1',
    ink: '#F2F5F1', inkSoft: '#D2DDD8', inkMuted: '#B4C3BE', primary: '#75C5AF', primaryHover: '#A0DCCA', primarySoft: '#263D38',
    primaryContrast: '#14211D', secondary: '#C8ABF0', accentWarm: '#F1A181', accentSun: '#E2C875',
    success: '#B5E6C5', warning: '#F4D89C', danger: '#F1B4B9', fontDisplay: 'Fraunces, Georgia, serif',
    successSoft: '#263D32', warningSoft: '#483B29', dangerSoft: '#482D34',
    successBorder: '#86B99A', warningBorder: '#D2A85F', dangerBorder: '#D78B96',
    fontBody: 'Manrope, sans-serif', fontLabel: 'IBM Plex Mono, monospace', radiusControl: '0.5rem',
    radiusPanel: '1rem', radiusHero: '1.5rem', motionFast: '120ms', motionStandard: '220ms', motionSpatial: '500ms',
  },
  artwork: {},
  viewLoaders: {
    OnboardingView: () => import('./views/OnboardingView.jsx'),
    TrailView: () => import('./views/TrailView.jsx'),
    SessionView: () => import('./views/SessionView.jsx'),
    CheckpointView: () => import('./views/CheckpointView.jsx'),
    ReviewQueueView: () => import('./views/ReviewQueueView.jsx'),
    ReviewSessionView: () => import('./views/ReviewSessionView.jsx'),
    BuildView: () => import('./views/BuildView.jsx'),
    ContinuationView: () => import('./views/ContinuationView.jsx'),
    SettingsView: () => import('./views/SettingsView.jsx'),
    SupportView: () => import('./views/SupportView.jsx'),
  },
}
