import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { compatibilityTokens, tokenName } from '../client/src/theme/tokens.js'
import { createThemeTokens, THEME_CATALOG } from '../client/src/theme/catalog.js'

const outputPath = resolve('client/src/styles/generated-themes.css')

function cssValue(value) {
  return String(value).replace(/\\/g, '\\\\').replace(/\n/g, '\\A ')
}

function render() {
  const blocks = THEME_CATALOG.map((entry) => {
    const tokens = createThemeTokens(entry)
    const declarations = Object.entries(tokens).map(([name, value]) => `  --${tokenName(name)}: ${cssValue(value)};`)
    for (const [name, token] of Object.entries(compatibilityTokens)) {
      if (tokens[token]) declarations.push(`  --${name}: ${cssValue(tokens[token])};`)
    }
    return `:root[data-theme="${entry.id}"] {\n${declarations.join('\n')}\n}`
  })
  return `/* Generated by scripts/generate-themes.mjs. Do not edit directly. */\n\n${blocks.join('\n\n')}\n`
}

const generated = render()
if (process.argv.includes('--check')) {
  let current = ''
  try {
    current = readFileSync(outputPath, 'utf8')
  } catch {
    process.exitCode = 1
  }
  if (current !== generated) {
    console.error(`Theme CSS is stale: ${outputPath}`)
    process.exitCode = 1
  }
} else {
  writeFileSync(outputPath, generated)
}
