export default {
  id: 'living-atlas',
  name: 'Living Atlas',
  mode: 'light',
  tagline: 'A calm, grounded map for steady learning.',
  previewAsset: '/themes/living-atlas.webp',
  tokens: {
    canvas: '#F1F5F3', panel: '#FFFEFA', elevated: '#FFFFFF', inset: '#E5ECE8', border: '#66766E', borderStrong: '#4C5D55',
    ink: '#23312C', inkSoft: '#44514B', inkMuted: '#5D6862', primary: '#3E7163', primaryHover: '#315E52',
    primaryContrast: '#FFFFFF', primarySoft: '#EAF3EF', secondary: '#765D88', accentWarm: '#A45F43', accentSun: '#A97924',
    success: '#28563A', warning: '#684719', danger: '#792F38', fontDisplay: 'Fraunces, Georgia, serif',
    successSoft: '#E7F2EA', warningSoft: '#FFF1D8', dangerSoft: '#FAE9EA',
    successBorder: '#557D62', warningBorder: '#96702F', dangerBorder: '#A95059',
    fontBody: 'Manrope, sans-serif', fontLabel: 'IBM Plex Mono, monospace', radiusControl: '0.5rem',
    radiusPanel: '1rem', radiusHero: '1.5rem', motionFast: '120ms', motionStandard: '220ms', motionSpatial: '500ms',
  },
  artwork: {},
  viewLoaders: {
    OnboardingView: () => import('./views/OnboardingView.jsx'),
    TrailView: () => import('./views/TrailView.jsx'),
    SessionView: () => import('./views/SessionView.jsx'),
    CheckpointView: () => import('./views/CheckpointView.jsx'),
    ReviewQueueView: () => import('./views/ReviewQueueView.jsx'),
    ReviewSessionView: () => import('./views/ReviewSessionView.jsx'),
    BuildView: () => import('./views/BuildView.jsx'),
    ContinuationView: () => import('./views/ContinuationView.jsx'),
    SettingsView: () => import('./views/SettingsView.jsx'),
    SupportView: () => import('./views/SupportView.jsx'),
  },
}
