export default {
  id: 'curiosity-engine',
  name: 'Curiosity Engine',
  mode: 'light',
  tagline: 'An energetic studio for exploring new ideas.',
  previewAsset: '/themes/curiosity-engine.webp',
  tokens: {
    canvas: '#F4F0E7', panel: '#FFFCF6', elevated: '#FFFFFF', inset: '#EDE4D5', border: '#66766E', borderStrong: '#4C5D55',
    ink: '#302B26', inkSoft: '#51483F', inkMuted: '#685E53', primary: '#665A92', primaryHover: '#504477',
    primaryContrast: '#FFFFFF', primarySoft: '#EFECF7', secondary: '#317C83', accentWarm: '#A64F3C', accentSun: '#A26D16',
    success: '#28563A', warning: '#684719', danger: '#792F38', fontDisplay: 'Fraunces, Georgia, serif',
    successSoft: '#E7F2EA', warningSoft: '#FFF1D8', dangerSoft: '#FAE9EA',
    successBorder: '#557D62', warningBorder: '#96702F', dangerBorder: '#A95059',
    fontBody: 'Manrope, sans-serif', fontLabel: 'IBM Plex Mono, monospace', radiusControl: '0.5rem',
    radiusPanel: '1rem', radiusHero: '1.5rem', motionFast: '120ms', motionStandard: '220ms', motionSpatial: '500ms',
  },
  artwork: {},
  viewLoaders: {
    OnboardingView: () => import('./views/OnboardingView.jsx'),
    TrailView: () => import('./views/TrailView.jsx'),
    SessionView: () => import('./views/SessionView.jsx'),
    CheckpointView: () => import('./views/CheckpointView.jsx'),
    ReviewQueueView: () => import('./views/ReviewQueueView.jsx'),
    ReviewSessionView: () => import('./views/ReviewSessionView.jsx'),
    BuildView: () => import('./views/BuildView.jsx'),
    ContinuationView: () => import('./views/ContinuationView.jsx'),
    SettingsView: () => import('./views/SettingsView.jsx'),
    SupportView: () => import('./views/SupportView.jsx'),
  },
}
